services:
  - type: web
    name: wa-manager
    runtime: node
    plan: free
    buildCommand: apt-get install -y chromium-browser && npm install
    startCommand: PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
    disk:
      name: sessions
      mountPath: /opt/render/project/src/sessions
      sizeGB: 1
